export const twinEntityLabels: Record<string, string> = {
  farms: 'Operações pecuárias',
  areas: 'Áreas',
  pastures: 'Pastos',
  cattle_lots: 'Lotes de gado',
  cattle_movements: 'Movimentações do rebanho',
  weighings: 'Pesagens',
  cattle_sales: 'Vendas do rebanho',
  sales: 'Vendas',
  employees: 'Funcionários',
  employee_payments: 'Pagamentos da equipe',
  inventory_items: 'Itens de estoque',
  inventory_movements: 'Movimentações de estoque',
  tasks: 'Tarefas',
  expenses: 'Despesas',
  revenues: 'Receitas',
  alerts: 'Alertas',
  documents: 'Documentos',
  gravel_operations: 'Operações de cascalho',
  suppression_operations: 'Operações de supressão',
  maintenance_records: 'Manutenções',
  occurrences: 'Ocorrências',
  ai_strategic_reports: 'Análises estratégicas',
  ai_strategic_insights: 'Achados estratégicos',
  autopilot_findings: 'Achados do Autopiloto',
  farm_goals: 'Metas da fazenda',
  planning_scenarios: 'Cenários de decisão',
  land_parcels: 'Propriedades rurais',
  farm_assets: 'Ativos operacionais',
  rural_contracts: 'Contratos rurais',
  rural_contract_installments: 'Parcelas de contratos',
  livestock_protocols: 'Protocolos sanitários e reprodutivos',
  livestock_protocol_executions: 'Execuções de manejo pecuário',
}

export const twinEventLabels: Record<string, string> = {
  baseline_imported: 'Linha de base importada',
  entity_created: 'Cadastro criado',
  entity_updated: 'Cadastro atualizado',
  entity_deleted: 'Cadastro excluído',
  entity_restored: 'Cadastro restaurado',
  status_changed: 'Status alterado',
  livestock_movement_recorded: 'Movimentação do rebanho registrada',
  weighing_recorded: 'Pesagem registrada',
  livestock_sale_recorded: 'Venda do rebanho registrada',
  expense_recorded: 'Despesa registrada',
  revenue_recorded: 'Receita registrada',
  inventory_movement_recorded: 'Movimentação de estoque registrada',
  employee_payment_recorded: 'Pagamento da equipe registrado',
  maintenance_recorded: 'Manutenção registrada',
  task_created: 'Tarefa criada',
  task_completed: 'Tarefa concluída',
  autopilot_finding_detected: 'Risco detectado pelo Autopiloto',
}

export const twinRelationLabels: Record<string, string> = {
  belongs_to_farm: 'pertence à operação',
  located_in_property: 'está na propriedade',
  belongs_to_area: 'pertence à área',
  located_in_pasture: 'está no pasto',
  related_to_pasture: 'relaciona-se ao pasto',
  belongs_to_cattle_lot: 'pertence ao lote',
  related_to_cattle_lot: 'relaciona-se ao lote',
  belongs_to_employee: 'pertence ao funcionário',
  assigned_to_employee: 'atribuída ao funcionário',
  related_to_employee: 'relaciona-se ao funcionário',
  belongs_to_inventory_item: 'pertence ao item',
  related_to_inventory_item: 'relaciona-se ao item',
  related_to_task: 'relaciona-se à tarefa',
  related_to_sale: 'relaciona-se à venda',
  related_to_expense: 'relaciona-se à despesa',
  supported_by_document: 'comprovada pelo documento',
  belongs_to_report: 'pertence à análise',
  originated_pending_action: 'originada pela ação pendente',
  moved_from_farm: 'saiu da propriedade',
  moved_to_farm: 'entrou na propriedade',
  moved_from_pasture: 'saiu do pasto',
  moved_to_pasture: 'entrou no pasto',
  related_to: 'relaciona-se a',
}

export const twinFieldLabels: Record<string, string> = {
  id: 'Identificador',
  status: 'Status',
  name: 'Nome',
  title: 'Título',
  full_name: 'Nome',
  description: 'Descrição',
  category: 'Categoria',
  subcategory: 'Subcategoria',
  origin: 'Origem',
  owner: 'Proprietário',
  type: 'Tipo',
  unit: 'Unidade',
  notes: 'Observações',
  created_at: 'Criado em',
  updated_at: 'Atualizado em',
  created_by: 'Criado por',
  current_quantity: 'Quantidade atual',
  approximate_capacity: 'Capacidade aproximada',
  approximate_size: 'Tamanho aproximado',
  current_condition: 'Condição atual',
  rest_status: 'Situação de descanso',
  amount: 'Valor',
  cost: 'Custo',
  price: 'Preço',
  expense_date: 'Data da despesa',
  revenue_date: 'Data da receita',
  payment_date: 'Data do pagamento',
  payment_method: 'Forma de pagamento',
  has_receipt: 'Possui comprovante',
  supplier_name: 'Fornecedor',
  due_date: 'Prazo',
  priority: 'Prioridade',
  completed_at: 'Conclusão',
  task_type: 'Tipo de tarefa',
  average_weight: 'Peso médio',
  quantity_weighed: 'Quantidade pesada',
  weighing_date: 'Data da pesagem',
  payment_status: 'Situação do pagamento',
  minimum_quantity: 'Estoque mínimo',
  maintenance_date: 'Data da manutenção',
  cost_amount: 'Custo',
  farm_id: 'Operação pecuária',
  related_farm_id: 'Operação relacionada',
  land_parcel_id: 'Propriedade rural',
  area_id: 'Área',
  pasture_id: 'Pasto',
  related_pasture_id: 'Pasto relacionado',
  cattle_lot_id: 'Lote',
  related_cattle_lot_id: 'Lote relacionado',
  assigned_to_employee_id: 'Responsável',
  assigned_to_user_id: 'Usuário responsável',
  related_employee_id: 'Funcionário relacionado',
  related_inventory_item_id: 'Item de estoque relacionado',
  related_task_id: 'Tarefa relacionada',
  source_message_id: 'Mensagem de origem',
  alert_type: 'Tipo de alerta',
  message: 'Mensagem',
  recipient_user_id: 'Destinatário',
  related_id: 'Registro relacionado',
  related_table: 'Módulo relacionado',
  sent_at: 'Enviado em',
  legal_name: 'Razão social',
  municipality: 'Município',
  state: 'Estado',
  total_area_ha: 'Área total (ha)',
  productive_area_ha: 'Área produtiva (ha)',
  primary_activity: 'Atividade principal',
  livestock_system: 'Sistema pecuário',
  location_description: 'Localização',
  metric: 'Indicador',
  target_value: 'Valor-alvo',
  target_date: 'Data-alvo',
  baseline_value: 'Valor inicial',
  template_type: 'Modelo do cenário',
  horizon_months: 'Horizonte (meses)',
  confidence_score: 'Confiança dos dados',
  linked_goal_id: 'Meta vinculada',
}

export const twinStatusLabels: Record<string, string> = {
  active: 'Ativo',
  inactive: 'Inativo',
  pending: 'Pendente',
  in_progress: 'Em andamento',
  completed: 'Concluído',
  cancelled: 'Cancelado',
  canceled: 'Cancelado',
  deleted: 'Excluído',
  paid: 'Pago',
  unpaid: 'Em aberto',
  overdue: 'Atrasado',
  scheduled: 'Agendado',
  sent: 'Enviado',
  failed: 'Falhou',
  draft: 'Rascunho',
  approved: 'Aprovado',
  rejected: 'Rejeitado',
  received: 'Recebido',
  expired: 'Vencido',
  terminated: 'Encerrado',
}

export const twinEntityRoutes: Record<string, string> = {
  farms: '/farms', pastures: '/pastures', cattle_lots: '/cattle',
  cattle_movements: '/cattle', weighings: '/weighings', cattle_sales: '/sales',
  employees: '/employees', employee_payments: '/employee-payments',
  inventory_items: '/inventory', inventory_movements: '/inventory-movements',
  tasks: '/tasks', expenses: '/finance', revenues: '/finance', alerts: '/alerts',
  documents: '/documents', gravel_operations: '/gravel-operations',
  suppression_operations: '/suppression-operations', maintenance_records: '/maintenance',
  occurrences: '/occurrences', ai_strategic_reports: '/intelligence',
  ai_strategic_insights: '/intelligence',
  autopilot_findings: '/autopilot',
  farm_goals: '/planning',
  planning_scenarios: '/planning',
  livestock_protocols: '/herd-health',
  livestock_protocol_executions: '/herd-health',
  land_parcels: '/farms',
  farm_assets: '/setup',
  rural_contracts: '/contracts',
  rural_contract_installments: '/contracts',
}

export function twinEntityLabel(value: string) {
  return twinEntityLabels[value] || value.replaceAll('_', ' ')
}

export function twinEventLabel(value: string) {
  return twinEventLabels[value] || value.replaceAll('_', ' ')
}

export function twinFieldLabel(value: string) {
  return twinFieldLabels[value] || value.replaceAll('_', ' ')
}

export function twinStatusLabel(value: string) {
  return twinStatusLabels[value] || value.replaceAll('_', ' ')
}
